apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../yamls

images:
- name: cloud-api-adaptor
  newName: quay.io/confidential-containers/cloud-api-adaptor # change image if needed
  newTag: latest

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- literals:
  - CLOUD_PROVIDER="libvirt"
  - LIBVIRT_URI="qemu:///system"
  - LIBVIRT_NET="default"
  - LIBVIRT_POOL="default"
  - LIBVIRT_VOL_NAME="podvm-base.qcow2"
  name: peer-pods-cm
  namespace: confidential-containers-system
  #- LIBVIRT_VOL_NAME="" # Uncomment and set if you want to use a specific volume name. Defaults to podvm-base.qcow2
  #- LIBVIRT_LAUNCH_SECURITY="" # sev or s390pv
  #- LIBVIRT_FIRMWARE="" # OVMF path (for SEV)
  #- LIBVIRT_FIRMWARE_VARS="" #OVMF_VARS path (for SEV)
  #- PAUSE_IMAGE="" # Uncomment and set if you want to use a specific pause image
  #- VXLAN_PORT="" # Uncomment and set if you want to use a specific vxlan port. Defaults to 4789
##TLS_SETTINGS
  #- CACERT_FILE="/etc/certificates/ca.crt" # for TLS
  #- CERT_FILE="/etc/certificates/client.crt" # for TLS
  #- CERT_KEY="/etc/certificates/client.key" # for TLS
  #- TLS_SKIP_VERIFY="" # for testing only
##TLS_SETTINGS

  #- auth.json # set - path to auth.json pull credentials file
secretGenerator:
- name: auth-json-secret
  namespace: confidential-containers-system
- files:
  - id_rsa
  name: ssh-key-secret
  namespace: confidential-containers-system
- name: peer-pods-secret
  namespace: confidential-containers-system
